### ISSUE TITLE
Confusing panic in `into_password`

### ISSUE THREAD

**Issue by elmaxxo** [sunng87/pgwire#181]
Are there any reasons to panic in [`into_password`](https://github.com/sunng87/pgwire/blob/0e2410359a58fbfcdc38d8b07181146d41e968fc/src/messages/startup.rs#L278-L281) and other `PasswordMessageFamily` methods? They already return `Result`, so I'd prefer to return an error if the passoword has a concrete type.

**Comment by sunng87** [comment]
Yes. By designing it as a panic, I hope to express that it's not a runtime error, but an invalid usage of the API. 

The background is that a few `Password` messages in wire protocol share the same message type code `p`. When we are decoding those messages without a context, it's impossible to tell the actual type. So we created `PasswordMessageFamily` struct and the initial state of it, after decoded from the wire, is always `Raw`.

For API level users, since you can only select one type of authentication method for a client, the actual type of `PasswordMessageFamily` must be known so you need to call the right `into_*` function.
